name: Update Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  documentation:
    runs-on: ubuntu-latest
    name: Documentation

    strategy:
      fail-fast: false
      matrix:
        python-version:
          [
            '3.10'
          ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install tools
        run: make build

      - name: Clean
        run: make dev

      - name: Build Documentation
        run: make docs

      - name: Copy to documentation Website Location
        run: |
          mkdir ../gh-pages
          cp -r doc/_build/html/* ../gh-pages/
          cd ../gh-pages
          touch .nojekyll
      - name: Commit documentation changes
        run: |
          echo ${{ github.ref }}
          echo "Commit documentation"
          # Set identity
          git config --global user.email "dev-git-action@paypal.com"
          git config --global user.name "Git Action Doc"

          git init
          git remote add origin https://${GH_TOKEN}@github.com/hyperwallet/python-sdk.git > /dev/null
          git checkout -B gh-pages
          git commit -m "Documentation updated" | exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
