name: Update Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  documentation:
    runs-on: ubuntu-latest
    name: Documentation

    strategy:
      fail-fast: false
      matrix:
        python-version:
          [
            '3.10'
          ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install tools
        run: make build

      - name: Clean
        run: make dev

      - name: Build Documentation
        run: make docs

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Documentation updated"
