name: Update Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  documentation:
    runs-on: ubuntu-latest
    name: Documentation

    strategy:
      fail-fast: false
      matrix:
        python-version:
          [
            '3.10'
          ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install tools
        run: make build

      - name: Clean
        run: make dev

      - name: Build Documentation
        run: make docs

      - name: Commit documentation changes
        run: |
          echo ${{ github.ref }}
          echo "Commit documentation"
          
          # Set identity
          git config --global user.email "dev-git-action@paypal.com"
          git config --global user.name "Git Action Doc"
          
          git checkout -B gh-pages
          git add .
          git commit -m "Documentation updated" 
          
          #push 
          git push origin gh-pages -fq > /dev/null | exit 0
